name: go_buddy_goo
description: Go Buddy Goo Mobile Application

publish_to: "none" 

version: 1.0.0+2

environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  auto_size_text: ^3.0.0
  bot_toast: ^4.0.3
  cached_network_image: ^3.2.2
  carousel_slider: ^4.1.1
  circular_profile_avatar: ^2.0.5
  connectivity_plus: ^3.0.2
  convex_bottom_bar: ^3.1.0+1
  cupertino_icons: ^1.0.2
  custom_date_range_picker: ^1.0.6
  date_time_format: ^2.0.1
  dio: ^4.0.6
  dots_indicator: ^2.1.0
  esewa_flutter_sdk:
    path: ./esewa_flutter_sdk
  faker: ^2.0.0
  firebase_core: ^2.1.1
  flare_flutter: ^3.0.2
  flutter:
    sdk: flutter
  flutter_animator: ^3.2.2
  flutter_bloc: ^8.1.1
  flutter_countdown_timer: ^4.1.0
  flutter_downloader: ^1.8.4
  flutter_image_compress: ^1.1.3
  flutter_rating_bar: ^4.0.1
  flutter_svg: ^1.1.5
  flutter_typeahead: ^4.1.1
  font_awesome_flutter: ^10.2.1
  form_field_validator: ^1.1.0
  geocoding: ^2.0.5
  geolocator: ^9.0.2
  get: ^4.6.5
  get_it: ^7.2.0
  google_fonts: ^3.0.1
  google_maps_flutter: ^2.2.1
  google_sign_in: ^5.4.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  image_picker: ^0.8.6
  infinite_scroll_pagination: ^3.2.0
  intl: ^0.17.0
  khalti: ^1.0.2
  khalti_flutter: ^2.1.0
  logger: ^1.1.0
  lottie: ^1.4.3
  maps_launcher: ^2.0.1
  package_info_plus: ^1.3.0
  path_provider: ^2.0.11
  percent_indicator: ^4.2.2
  permission_handler: ^10.1.0
  persistent_bottom_nav_bar: ^5.0.2
  photo_view: ^0.14.0
  pin_code_fields: ^7.4.0
  random_string: ^2.3.1
  readmore: ^2.2.0
  recase: ^4.1.0
  rename: ^2.0.1
  shimmer: ^2.0.0
  sms_autofill: ^2.2.0
  syncfusion_flutter_sliders: ^20.3.61
  timeago: ^3.3.0
  url_launcher: ^6.1.6

dev_dependencies:
  build_runner: ^2.3.0
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.11.0

  flutter_test:
    sdk: flutter
  hive_generator: ^1.1.3
  pretty_dio_logger: ^1.1.1

flutter_icons:
  android: true
  ios: true 
  image_path: "assets/images/logo1024.png"

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/lang/
    - assets/json/
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
